apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name}}
  labels:
    {{- include "mysql-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort}}
      protocol: TCP
      name: http
  selector:
    {{- include "mysql-chart.selectorLabels" . | nindent 4 }}
