server: 
    port: 8081
    
spring:
    datasource:
#        url: jdbc:mysql://${DB_HOST}/${DB_NAME}
        url: jdbc:mysql://localhost:3306/organizationdb
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 1234
#        username: ${DB_USERNAME}
#        password: ${DB_PASSWORD}
    jpa: 
        database-platform: org.hibernate.dialect.MySQL5Dialect
        hibernate: 
            ddl-auto: update

# server.port:8080
# #spring.datasource.url=jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=false
# spring.datasource.url=jdbc:mysql://mysql/organizationdb
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.datasource.username=root
# spring.datasource.password=1234
# # spring.datasource.username=${DB_USERNAME}
# # spring.datasource.password=${DB_PASSWORD}
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
# spring.application.name=organization-service
# #eureka.instance.hostname=localhost